### ISSUE TITLE
limit_clause() got an unexpected keyword argument 'literal_binds'

### ISSUE THREAD

**Issue by gbrian** [gijzelaerr/sqlalchemy-monetdb#6]
Hi,

MonetCompiler does not overrides properly the **limit_clause** function.
Current implementation expects 1 argument but 2 are used by SQLAlchemy compiler.

    def limit_clause(self, select, **kw):
        ....

by fixing this I'm able to bypass the error.

**Comment by gijzelaerr** [comment]
hi gbrian,

what version of SQLAlchemy are you using? Maybe the API changed.

**Comment by gbrian** [comment]
Hi, 
Yep, I guess they changed. This is from SQLAlchemy\__init__.py
**__version__ = '1.0.8'**
I just ran "pip install SQLAlchemy" so I guess last one. 

BTW the fix worked for me.

**Comment by gijzelaerr** [comment]
ok thx.

Do you know how to issue a pull request? If so can you issue a pull request with this change?

thanks,

 - Gijs

**Comment by gijzelaerr** [comment]
Btw, congrats, you are the first person who reports a bug here since the 2.5 years this project exists :)

**Comment by gbrian** [comment]
Sure, let me fix that! 
Your project is being quite useful for me and I expect for others soon.
I've connected the Panoramix project with MonetDB thanks to your code and (Panoramix guys, ofc! ;) )
I'll keep you posted.
Panoramix: https://github.com/mistercrunch/panoramix

**Comment by gijzelaerr** [comment]
awesome, good to hear somebody is using it. I never finished this project 100%, but if you have PR's to make it better i'm more than happy to review and merge them.

Please make sure the test suite runs. I think i'm still testing with 0.9 in the travis files since that was the latest version when i was working on this project. Would be awesome if the test suite runs with both 0.9 and 1.0.*

**Comment by gbrian** [comment]
Just FYI found this, seems to be the reason for the change:
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/6.2_Technical_Notes/python-sqlalchemy.html

**Comment by aalexandrov** [comment]
Any progress on that or pointers for a quick fix?

I am trying to setup `sqlalchemy-monetdb` from [Caravel](http://airbnb.io/caravel/installation.html#database-dependencies).

**Comment by gijzelaerr** [comment]
I didn't work on this, but feel free to try to fix it yourself and do a pull request.

**Comment by aalexandrov** [comment]
@gijzelaerr Thanks, I will give it a shot.

I looked at @gbrian's for but couldn't find any fixup branch for that issue on his for. 

I was able to fix the problem locally after adding the `**kw` to `compiler.py` and recompiling `/usr/local/lib/python2.7/dist-packages/sqlalchemy_monetdb/compiler.py` directly.

I will check for migration pointers and other implementations for other database vendors to look for a better solution. Pointers are appreciated.

**Comment by gijzelaerr** [comment]
well if you commit and push your patch to a fork of this repo followed by a pull request I will accept it.

**Comment by gbrian** [comment]
Hi,

My fault, never finished it, sorry.
In my case was enough by fixing the function signature:

`def limit_clause(self, select, **kw):
        text = ""
        if select._limit is not None:
            text += "\nLIMIT " + str(select._limit)
        if select._offset is not None:
            text += " OFFSET " + str(select._offset)
        return text`

Note the extra "**kw" at the end. Hope this helps.

**Comment by gbrian** [comment]
https://github.com/gijzelaerr/sqlalchemy-monetdb/pull/7

Sorry for the delay :(

**Comment by gijzelaerr** [comment]
fixed by https://github.com/gijzelaerr/sqlalchemy-monetdb/pull/7

**Comment by gijzelaerr** [comment]
made a new release 0.9.2:

https://github.com/gijzelaerr/sqlalchemy-monetdb/releases/tag/0.9.2

also available on pypi:

https://pypi.python.org/pypi/sqlalchemy_monetdb

enjoy, and if you find more problems please do an other PR.

**Comment by aalexandrov** [comment]
Wow, that was fast :)

**Comment by aalexandrov** [comment]
Thanks @gbrian and @gijzelaerr.
